[package]
name = "scte35-reader"
version = "0.1.0"
authors = ["David Holroyd <dave@badgers-in-foil.co.uk>"]
description = "Reader for data formatted according to SCTE-35"

[dependencies]
mpeg2ts-reader = "0.1.0"
bitreader = "0.3.1"


[dev-dependencies]
hex-literal = "0.1.0"
matches = "0.1.6"
